### ISSUE TITLE
Function refusing to build.

### ISSUE THREAD

**Issue by virtadpt** [esimov/colidr-openfaas#1]
Following instructions in readme results in the following output:
```
drwho@stupidmac: openfaas-coherent-line-drawing$ faas-cli build -f stack.yml
2019/07/17 09:15:34 No templates found in current directory.
2019/07/17 09:15:34 Attempting to expand templates from https://github.com/openfaas/templates.git
2019/07/17 09:15:35 Fetched 16 template(s) : [csharp csharp-armhf dockerfile dockerfile-armhf go go-armhf java8 node node-arm64 node-armhf php7 python python-armhf python3 python3-armhf ruby] from https://github.com/openfaas/templates.git
[0] > Building coherent-line-drawing.
2019/07/17 09:15:35 language template: go-opencv not supported, build a custom Dockerfile
[0] < Building coherent-line-drawing done.
[0] worker done.
```
Platform: MacOSX 10.13.6
Docker: Docker Desktop v2.0.0.3, Engine v18.09.2, Notary v0.6.1, Compose v1.23.2, Credential Helper v0.6.0, Machine v0.16.1, Kubernetes v1.10.11
OpenFaaS: CLI v0.8.14, Gateway v0.13.9, faas-swarm v0.6.2

**Comment by virtadpt** [comment]
The following command had to be executed before the image would build:
```
faas-cli template pull https://github.com/alexellis/opencv-openfaas-template
```
After which, the function was successfully deployed.  However, there seems to be an upper limit on image size - 3000x3000 pixels is too much.

**Comment by esimov** [comment]
Try to increase the `write_timeout` in stack.yml

**Comment by esimov** [comment]
I will close this issue. If you are still facing the issue, you can reopen it.
